Added check for DOCKR_PORT .env variable

diff --git a/dockr b/dockr
--- a/dockr
+++ b/dockr
@@ -36,6 +36,13 @@ if [ -f "${PROJECT_ROOT_DIR}/.env" ]; then
     source "${PROJECT_ROOT_DIR}/.env"
 fi
 
+# Check for Mandatory Env variables
+if [ -z "${DOCKR_PORT}" ]; then
+    echo -e "Required Parameter ${YELLOW}\"DOCKR_PORT\"${CLR} is ${RED}missing${CLR} from ${CYAN}.env${CLR}"
+
+    exit 1
+fi
+
 # Container Name
 export DOCKR_CONTAINER_NAME=${DOCKR_CONTAINER_NAME:-"${PROJECT_NAME}-web"}
 
