- Error handling in proxy handler. - config "--get" option changed to "get" - Option for adding additional compose file
Signed-off-by: Sharan <sharan@mallow-tech.com>

diff --git a/res/bin/common/proxy b/res/bin/common/proxy
--- a/res/bin/common/proxy
+++ b/res/bin/common/proxy
@@ -34,8 +34,16 @@ check_site_in_proxy_container() {
 add_site_to_proxy_container() {
     echo -e "\n${PROCESS}Setting up proxy..."
 
-    DT_PROXY_SITE="http://host.docker.internal:${DT_PORT}"
-    docker-compose -f "${DOCKR_COMPOSE_ASSET}" -p "${DOCKR_ASSET_PROJECT_NAME}" exec proxy bash -c "add-listener ${DOCKR_SITE} ${DT_PROXY_SITE} >> /dev/null"
+    if [ "${DT_PORT}" != "" ]; then
+        DT_PROXY_SITE="http://host.docker.internal:${DT_PORT}"
+        docker-compose -f "${DOCKR_COMPOSE_ASSET}" -p "${DOCKR_ASSET_PROJECT_NAME}" exec proxy bash -c "add-listener ${DOCKR_SITE} ${DT_PROXY_SITE} >> /dev/null"
 
-    sleep 2
+        sleep 2
+
+    # Unable to fetch port from container.
+    else
+        echo -e "${RED}Unable${CLR} to set proxy. Please check your configuration."
+
+        exit 1
+    fi
 }
